### ISSUE TITLE
How to fix Android and Roku connection issues

### ISSUE THREAD

**Issue by todaywasawesome** [munnerz/kube-plex#107]
When using an iOS device or the web the Plex interface shows right up. When using Roku or Android is usually doesn't work though refreshing lots of times sometimes works. This is because Plex uses different ports for advertising services to Roku and Android and unfortunately they use both UDP and TCP.

You'll need to do some yak shaving to enabling all of these ports https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/#:~:text=The%20most%20important%20port%20to,Plex%20Media%20Server)%20%5Brequired%5D

Including using two load balancers with the same ip so I can have both UDP and TCP enabled. I have this working with metallb but am not sure how to approach it using other load balancer providers. 

Here's how the deployment yaml needs to look:
```
        ports:
          - name: pms
            containerPort: 32400
          - name: http
            containerPort: 32400
          - name: https
            containerPort: 32443
          - name: dlna
            containerPort: 1900
            protocol: UDP
          - name: pht 
            containerPort: 3005
          - name: avahi
            containerPort: 5353
            protocol: UDP
          - name: roku
            containerPort: 8324
          - name: gdm
            containerPort: 32410
            protocol: UDP
          - name: gdm2
            containerPort: 32412
            protocol: UDP
          - name: gdm3
            containerPort: 32413
            protocol: UDP
          - name: gdm4
            containerPort: 32414
            protocol: UDP
          - name: dlna2
            containerPort: 32469
```

I can prepare a PR but I'm not sure how to approach the creation of a 2nd loadbalancer that needs to happen.
