### ISSUE TITLE
Container plex failed liveness probe, will be restarted

### ISSUE THREAD

**Issue by cjriemens** [munnerz/kube-plex#110]
is there anyone who can help me with the following problem?

This is my first time working with kubernetes. and I run into the problem that my pod keeps restarting every time.

in error.txt I made a copy of kubectl describe pod
if someone can help me with this would be great
[error.txt](https://github.com/munnerz/kube-plex/files/5684956/error.txt)

Is it true that under service / plex-kube-plex there is no external ip?

# kubectl get all -n plex
NAME READY STATUS RESTARTS AGE
pod / plex-kube-plex-589f45bb6c-42pqg 0/1 CrashLoopBackOff 7 14m

NAME TYPE CLUSTER-IP EXTERNAL-IP PORT (S) AGE
service / plex-kube-plex ClusterIP 10.100.101.119 <none> 32400 / TCP, 80 / TCP, 443 / TCP 14m

NAME READY UP-TO-DATE AVAILABLE AGE
deployment.apps / plex-kube-plex 0/1 1 0 14m

NAME DESIRED CURRENT READY AGE
replicaset.apps / plex-kube-plex-589f45bb6c 1 1 0 14m

**Comment by jr0dd** [comment]
I'm using a TCP probe on port 32400. Although this works, I'm looking for something more precision for startup, liveness & readiness

**Comment by jump912** [comment]
I'm also facing the same problem. From the pod's event, there's a message "Readiness probe failed: Get "http://10.1.221.248:32400/identity": dial tcp 10.1.221.248:32400: connect: connection refused". 10.1.221.248 is the pod's cluster IP. However, when i try calling the /identity URI through the LoadBalancer ip (http://<LoadBalancerIP>:32400/identity), i gets a respond with the machine identifier. why then, the pod fails to read the identity through its own cluster IP? is there a way to fix this?

**Comment by jump912** [comment]
Updates:

I exec into the pod's shell and ran the following curl. as it turn out, the pod have no problem accessing the /identity URI. then what gives the error event?

I left the whoami and the first curl here in case that meant something.

# whoami
root

# curl http://10.1.221.248:32400
<html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>


# curl http://10.1.221.248:32400/identity
`MediaContainer size="0" claimed="1" machineIdentifier="64616bb75d750151caf6f06b83bc2e0e1d9a49c" version="1.24.3.5033-757abe6b4"`

**Comment by manuelkasiske** [comment]
I faced the same problem. It went better after I scalled up to a replica count of 2.

**Comment by ianhundere** [comment]
i've run into this issue before. i can't seem to figure out the cause. i thought it was maybe resources, but i've given 4gb for mem and 4000m cpu.

i'll try bumping the replica count up 🤞

**Comment by manuelkasiske** [comment]
@ianhundere : True, it corrupts the db, if you run plex on multiple nodes. I just run 2 instances on the same node. This works.

**Comment by RogerSik** [comment]
Same issue here. My Workaround is to do the healthcheck with curl inside the container.

```
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - 'curl -s http://localhost:32400/identity | grep -q "MediaContainer"'
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - 'curl -s http://localhost:32400/identity | grep -q "MediaContainer"'
            periodSeconds: 10
            failureThreshold: 6
```
