### ISSUE TITLE
--set ingress.enabled=true does not work with latest kubernetes, what else do i need to add to my ingress?

### ISSUE THREAD

**Issue by karezza** [munnerz/kube-plex#116]
The error went by quick but looks like the ingress api version used by this chart is no longer supported w/ kube v1.22.1.

I created my own ingress and pointed it at 32400.

I can log in and it detects my old docker-based server and I can watch videos hosted over there but it doesn't see this new server.  I was looking to configure the server as documented in step 4, but have been unable to proceed.

Is there something else I need to add to my ingress for the interface to see the new plex server?

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  namespace: plex
  annotations:
    #nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - plex.k-dev.mydomain.net
    secretName: plex
  rules:
  - host: plex.k-dev.mydomain.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plex-kube-plex
            port:
              number: 32400
```
