### ISSUE TITLE
Feature Request : More customization on Charts from values.yaml

### ISSUE THREAD

**Issue by SebastienTolron** [munnerz/kube-plex#21]
Hi Munnerz !

First of all , really great job on this helm chart. Works like a charm ! 

I had to make some customizations , and I think It can be pretty good to include them in the base chart.

Here is what would be good I think : 

* Provide some parameters for volumes :  Some people will need to use a NFS for making this to work. You should probably allow more customizations on volumes. For exemple , I had to change the volumes sections for shared  
```
      - name: shared
        flexVolume:
          driver: rook.io/rook
          fsType: ceph
          options:
            fsName: nfs-plex 
            clusterName: rook 
```
That would be good to provide the entire config in values.yml if needed to customize it.

* SecurityContext : This is related. You should provide option to allow customize securityContext  , so right will be managed properly on NFS

* Ingress : A basic ingress rule would be pretty cool for this chart :)

* PLEX_GID : This would be very good to have a parameter for that. 

Well this is a lot , and I customized that for my need , but I'm pretty sure people would love this in order to allow more customizations from values.yaml.

I know this can be a lot of work , but let me know what do you think about this , and I can help if needed. 

Keep rocking :grinning:
