### ISSUE TITLE
Extra Data mounts are not also mounted in transcoder pod, transcoding fails

### ISSUE THREAD

**Issue by runecalico** [munnerz/kube-plex#94]
Having the persistence.extraData mount options in the helm chart is super awesome as I don't have all of my media under a single share .. Unfortunately it looks like when the transcoder pod is created, it doesn't pass any of the extraData mounts to the transcoder, so attempts to transcode any file contained in one of those extraData mounts fails.
The transcoder pod deployment yaml doesn't show those extraData mounts ..
```
    volumeMounts:
    - mountPath: /data
      name: data
      readOnly: true
    - mountPath: /config
      name: config
      readOnly: true
    - mountPath: /transcode
      name: transcode
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-9shvd
      readOnly: true
    workingDir: /transcode/Transcode/Sessions/plex-transcode-d48pgie0z4f612e7g3ih5qhs-d18c2e9c-f4dc-49a7-9362-ecad21e9dc04
```

Unfortunately I'm a total noob with Go, so while I think the relevant code is in kube-plex\main.go, I don't really know how to ADD support for those extraData mounts (especially since there could be 0 or more of them).

Please Advise.
